import NextAuthProvider from '@/Provider/NextAuth';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

import './globals.css';
import Sidebar from '@/components/sidebar';
import Header from '@/components/header';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<NextAuthProvider>
					<main className='w-full h-screen overflow-hidden bg-[#000] text-white'>
						<Header />
						<section className='flex'>
							<Sidebar />
							{children}
						</section>
						<Toaster />
					</main>
				</NextAuthProvider>
			</body>
		</html>
	);
}
