import './globals.css';
import '@uploadthing/react/styles.css';

import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import { Header, Sidebar, SuggestedCommunities } from '@/components/index';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body>
					<main className=' h-screen w-full max-w-[1470px] overflow-hidden bg-black text-white'>
						<Header />
						<section className='flex h-screen w-full'>
							<Sidebar />
							{children}
							<SuggestedCommunities />
						</section>
					</main>
					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	);
}
