import './globals.css';
import '@uploadthing/react/styles.css';

import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='en'>
			<ClerkProvider>
				<body>
					{children}
					<Toaster />
				</body>
			</ClerkProvider>
		</html>
	);
}
